---
apiVersion: v1
kind: ConfigMap
metadata:
  name: geth-cm
data:
  genesis.json: {{ toYaml .Values.node.files.genesis | indent 2 }}
  init.sh: {{ toYaml .Values.node.files.init | indent 2 }}
  password.txt: ""
