{{- if .Values.node.enabled }}
{{- if .Values.node.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-node
spec:
  storageClassName: {{ .Values.node.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  {{- with .Values.node.persistence.existingPV }}
  volumeName: {{ . | toYaml | nindent 6 }}
  {{- end }}
  resources:
    requests:
      storage: {{ pluck $.Values.global.env .Values.node.persistence.storage | first | default .Values.node.persistence.storage._default | quote }}
---
{{- end }}
{{- if .Values.node.dtl.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-dtl
spec:
  storageClassName: {{ .Values.node.dtl.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  {{- with .Values.node.dtl.persistence.existingPV }}
  volumeName: {{ . | toYaml | nindent 6 }}
  {{- end }}
  resources:
    requests:
      storage: {{ pluck $.Values.global.env .Values.node.dtl.persistence.storage | first | default .Values.node.dtl.persistence.storage._default | quote }}
---
{{- end }}

{{- end }}
