{{- if .Values.node.enabled }}
{{- if .Values.node.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-node
spec:
  storageClassName: {{ .Values.node.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.node.persistence.storage }}
---
{{- end }}
{{- if .Values.node.dtl.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-dtl
spec:
  storageClassName: {{ .Values.node.dtl.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.node.dtl.persistence.storage }}
---
{{- end }}

{{- end }}
