{{- if .Values.node.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-geth
spec:
  serviceName: {{ .Release.Name }}-geth
  replicas: {{ .Values.node.replicas.app }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-geth
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-geth
    spec:
      containers:
      - name: {{ .Release.Name }}-geth
        image: {{ pluck $.Values.global.env .Values.node.image | first | default .Values.node.image._default | quote }}
        command: {{ .Values.node.command }}
        args: {{ .Values.node.args }}
        # args: [ "--http", "--http.addr=0.0.0.0", "--http.vhosts=geth-mainnet-full", "--http.api=eth,net,web3,txpool", "--ws", "--ws.addr=0.0.0.0", "--datadir=/data", ]
        resources:
        {{- with .Values.node.resources }}
          limits:
            memory: {{ pluck $.Values.global.env .limits.memory | first | default .limits.memory._default | quote }}
            cpu: {{ pluck $.Values.global.env .limits.cpu | first | default .limits.cpu._default | quote }}
          requests:
            memory: {{ pluck $.Values.global.env .requests.memory | first | default .requests.memory._default | quote }}
            cpu: {{ pluck $.Values.global.env .requests.cpu | first | default .requests.cpu._default | quote }}
        {{- end }}
        env:
{{- include "node_env" . | indent 10 }}
        ports:
          - containerPort: {{ .Values.node.portHttp }}
            name: gethrpchttp
          - containerPort: {{ .Values.node.portWs }}
            name: gethrpctcp
          - containerPort: {{ .Values.node.portDiscovery }}
            name: gethdiscovery
        volumeMounts:
        {{- .Values.node.persistence.enabled }}
          - name: data
            mountPath: "/data"
        {{- end }}
          - mountPath: /root/init.sh
            name: geth-cm
            subPath: init.sh
          - mountPath: /root/genesis.json
            name: geth-cm
            subPath: genesis.json
          - mountPath: /root/password.txt
            name: geth-cm
            subPath: password.txt
      {{- if .Values.node.nodeSelector.enabled }}
      nodeSelector:
        app: {{ .Values.node.nodeSelector.app}}
      {{- end }}
      volumes:
        - configMap:
            name: geth-cm
          name: geth-cm
  {{- .Values.node.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        # storageClassName: gp2
        resources:
          requests:
            storage: 1000Gi
  {{- end }}
---
{{- end }}
