{{- if .Values.postgres.enabled }}
{{- if .Values.postgres.persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pv-claim
spec:
  storageClassName: {{ .Values.postgres.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage | quote }}
---
{{- end }}

{{- end }}
