{{- if .Values.scVerifier.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: sc-verifier-svc
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
  #   service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  #   service.beta.kubernetes.io/aws-load-balancer-type: external
  labels:
    app: {{ .Release.Name }}-sc-verifier
spec:
  type: {{ .Values.scVerifier.service.type}}
  ports:
  {{- range $key, $value := .Values.scVerifier.ports }}
    - port: {{ toYaml $value.number | indent 2 }}
      targetPort: {{ toYaml $value.number | indent 2 }}
      protocol: {{ toYaml $value.protocol | indent 2 }}
      name: {{ $key }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}-sc-verifier
{{- end }}
---
