{{- if .Values.geth.enabled }}
{{- if .Values.geth.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-geth
spec:
  storageClassName: {{ .Values.geth.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  {{- with .Values.geth.persistence.existingPV }}
  volumeName: {{ . | toYaml | nindent 6 }}
  {{- end }}
  resources:
    requests:
      storage: {{ pluck $.Values.global.env .Values.geth.persistence.storage | first | default .Values.geth.persistence.storage._default | quote }}
---
{{- end }}
{{- if .Values.geth.client.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-client
spec:
  storageClassName: {{ .Values.geth.client.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  {{- with .Values.geth.client.persistence.existingPV }}
  volumeName: {{ . | toYaml | nindent 6 }}
  {{- end }}
  resources:
    requests:
      storage: {{ pluck $.Values.global.env .Values.geth.client.persistence.storage | first | default .Values.geth.client.persistence.storage._default | quote }}
---
{{- end }}

{{- end }}
