name: QA pipeline
on:
  workflow_dispatch:
    inputs:
      blockscout_image:
        description: 'Blockscout image:tag to test'     
        required: true
        default: 'blockscout/blockscout:latest' 
        type: string
      environment:
        description: 'Environment to run tests against'
        required: true
        type: choice
        default: 'test'
        options:
        - prod
        - test
  workflow_call:
    inputs:
      blockscout_image:
        description: 'Blockscout image:tag to test'     
        required: true
        default: 'blockscout/blockscout:latest' 
        type: string
      environment:
        description: 'Environment to run tests against'
        required: true
        type: string
        default: 'test'
jobs:
  tests:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - uses: blockscout/blockscout-ci-cd/.github/workflows/e2e.yaml@master
        with:
          environment: test
      - uses: blockscout/blockscout-ci-cd/.github/workflows/load_baseline.yaml@master
        with:
          environment: test