{{- if .Values.adminRs.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-admin-rs
spec:
  replicas: {{ .Values.adminRs.replicas.app }}
  strategy:
    type: {{ .Values.adminRs.strategy }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-admin-rs
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-admin-rs
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: {{ .Release.Name }}-admin-rs
          image: {{ pluck $.Values.global.env .Values.adminRs.image | first | default .Values.adminRs.image._default | quote }}
          resources:
          {{- with .Values.adminRs.resources }}
            limits:
              memory: {{ pluck $.Values.global.env .limits.memory | first | default .limits.memory._default | quote }}
              cpu: {{ pluck $.Values.global.env .limits.cpu | first | default .limits.cpu._default | quote }}
            requests:
              memory: {{ pluck $.Values.global.env .requests.memory | first | default .requests.memory._default | quote }}
              cpu: {{ pluck $.Values.global.env .requests.cpu | first | default .requests.cpu._default | quote }}
          {{- end }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.adminRs.docker.targetPort }}
            # - containerPort: {{ .Values.adminRs.docker.metricsPort }}
            #   name: http-metrics
          env:
{{- include "adminRs_env" . | indent 10 }}
          # volumeMounts:
          #   - name: {{ .Release.Name }}-logs
          #     mountPath: /usr/local/path
          {{- if .Values.adminRs.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.adminRs.readinessProbe.path }}
              port: {{ .Values.adminRs.docker.targetPort }}
              scheme: HTTP
            {{- with .Values.adminRs.readinessProbe.params }}
            {{ . | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.adminRs.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.adminRs.livenessProbe.path }}
              port: {{ .Values.adminRs.docker.targetPort }}
              scheme: HTTP
            {{- with .Values.adminRs.livenessProbe.params }}
            {{ . | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
      # volumes:
      #   - name: {{ .Release.Name }}-logs
      #     emptyDir: { }
      #   - name: config
      #     configMap:
      #       name: {{ .Release.Name }}-promtail-configmap
      restartPolicy: Always
      {{- if .Values.adminRs.nodeSelector.enabled }}
      nodeSelector:
      {{- pluck $.Values.global.env .Values.adminRs.nodeSelector.labels | first | default .Values.adminRs.nodeSelector.labels._default | toYaml | nindent 8 }}
      {{- end }}
---
{{- end}}
